Sphinx autodoc mock_imports added
sphinx-doc/sphinx-argparse pull request #35
Opened 2023-02-14 15:41 UTC by prajeeshag

Sphinx autodoc_mock_imports is implemented here. 
https://github.com/ashb/sphinx-argparse/issues/9#issue-1097057823

2024-05-01 13:22 UTC, ashb requested changes
Please add some unit tests for this.

2024-05-01 13:23 UTC, ashb commented on sphinxarg/ext.py
> +from sphinx.ext.autodoc import mock
Could this import ever fail? I forget if autodoc is shipped with Sphinx or an extra module that needs to be installed.

2024-07-15 15:52 UTC, merged

2024-07-16 22:03 UTC, mark-nicholson commented
Something is awry with this commit.  I get a crash at that first line.  version 0.4.0 work like a champ for a long time.
```
  File "/u02/masatest/mjnichol-3.6.1.dev1-bscrub-311/venv/lib64/python3.11/site-packages/sphinxarg/ext.py", line 509, in run
    with mock(self.config.autodoc_mock_imports):
              ^^^^^^^^^^^
AttributeError: 'ArgParseDirective' object has no attribute 'config'
```

2024-07-17 10:05 UTC, AA-Turner commented
Fixed in 11bfc2bbc0fec600acd1d59e3cfa4d8e92379eb7; sorry. See also #56.

A